version: '2'

services:
    ca.org1.oslab.com:
        image: hyperledger/fabric-ca:1.4.4
        environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.org1.oslab.com
        - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.oslab.com-cert.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca1_key
        # - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.org1.oslab.com-cert.pem
        - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/ca1_tls_key
        # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/key.pem

        ports:
        - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
        - ../../config/pbft/crypto-config/peerOrganizations/org1.oslab.com/ca/:/etc/hyperledger/fabric-ca-server-config
        - ../../config/pbft/crypto-config/peerOrganizations/org1.oslab.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
        container_name: ca.org1.oslab.com

    ca.org2.oslab.com:    
        image: hyperledger/fabric-ca:1.4.4
        environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.org2.oslab.com
        - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.oslab.com-cert.pem
        - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ca2_key
        # - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/key.pem
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-tls/tlsca.org2.oslab.com-cert.pem
        - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/ca2_tls_key
        # - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-tls/key.pem

        ports:
        - "8054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
        - ../../config/pbft/crypto-config/peerOrganizations/org2.oslab.com/ca/:/etc/hyperledger/fabric-ca-server-config
        - ../../config/pbft/crypto-config/peerOrganizations/org2.oslab.com/tlsca/:/etc/hyperledger/fabric-ca-server-tls
        container_name: ca.org2.oslab.com

    orderer0.oslab.com:
        container_name: orderer0.oslab.com
        image: hyperledger/fabric-orderer:amd64-latest
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - ORDERER_GENERAL_LISTENPORT=6050
        - PBFT_LISTEN_PORT=6070
        - PBFT_NODE_ID=0
        - PBFT_NODE_TABLE=http://orderer0.oslab.com:6070;http://orderer1.oslab.com:6071;http://orderer2.oslab.com:6072;http://orderer3.oslab.com:6073
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        ports:
        - 6050:6050
        - 6070:6070
        volumes:
        - ../../config/pbft/channel-artifacts:/etc/hyperledger/configtx
        - ../../config/pbft/crypto-config/ordererOrganizations/oslab.com/orderers/orderer0.oslab.com/:/etc/hyperledger/msp/orderer
        depends_on:
        - ca.org1.oslab.com
  
    orderer1.oslab.com:
        container_name: orderer1.oslab.com
        image: hyperledger/fabric-orderer:amd64-latest
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - ORDERER_GENERAL_LISTENPORT=6051
        - PBFT_LISTEN_PORT=6071
        - PBFT_NODE_ID=1
        - PBFT_NODE_TABLE=http://orderer0.oslab.com:6070;http://orderer1.oslab.com:6071;http://orderer2.oslab.com:6072;http://orderer3.oslab.com:6073
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        ports:
        - 6051:6051
        - 6071:6071
        volumes:
        - ../../config/pbft/channel-artifacts:/etc/hyperledger/configtx
        - ../../config/pbft/crypto-config/ordererOrganizations/oslab.com/orderers/orderer1.oslab.com/:/etc/hyperledger/msp/orderer
        depends_on:
        - ca.org1.oslab.com

    orderer2.oslab.com:
        container_name: orderer2.oslab.com
        image: hyperledger/fabric-orderer:amd64-latest
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - ORDERER_GENERAL_LISTENPORT=6052
        - PBFT_LISTEN_PORT=6072
        - PBFT_NODE_ID=2
        - PBFT_NODE_TABLE=http://orderer0.oslab.com:6070;http://orderer1.oslab.com:6071;http://orderer2.oslab.com:6072;http://orderer3.oslab.com:6073
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        ports:
        - 6052:6052
        - 6072:6072
        volumes:
        - ../../config/pbft/channel-artifacts:/etc/hyperledger/configtx
        - ../../config/pbft/crypto-config/ordererOrganizations/oslab.com/orderers/orderer2.oslab.com/:/etc/hyperledger/msp/orderer
        depends_on:
        - ca.org1.oslab.com

    orderer3.oslab.com:
        container_name: orderer3.oslab.com
        image: hyperledger/fabric-orderer:amd64-latest
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - ORDERER_GENERAL_LISTENPORT=6053
        - PBFT_LISTEN_PORT=6073
        - PBFT_NODE_ID=3
        - PBFT_NODE_TABLE=http://orderer0.oslab.com:6070;http://orderer1.oslab.com:6071;http://orderer2.oslab.com:6072;http://orderer3.oslab.com:6073
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        ports:
        - 6053:6053
        - 6073:6073
        volumes:
        - ../../config/pbft/channel-artifacts:/etc/hyperledger/configtx
        - ../../config/pbft/crypto-config/ordererOrganizations/oslab.com/orderers/orderer3.oslab.com/:/etc/hyperledger/msp/orderer
        depends_on:
        - ca.org1.oslab.com

    peer0.org1.oslab.com:
        container_name: peer0.org1.oslab.com
        image: hyperledger/fabric-peer:1.4.4
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - CORE_LOGGING_LEVEL=ERROR
        - CORE_CHAINCODE_LOGGING_LEVEL=ERROR
        - CORE_CHAINCODE_LOGGING_SHIM=ERROR
        - CORE_CHAINCODE_EXECUTETIMEOUT=999999
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_PEER_ID=peer0.org1.oslab.com
        - CORE_PEER_ENDORSER_ENABLED=true
        - CORE_PEER_LOCALMSPID=Org1MSP
        - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp/
        - CORE_PEER_ADDRESS=peer0.org1.oslab.com:7051
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.oslab.com:7051
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/peer/tls/server.key
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/peer/tls/server.crt
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/tls/ca.crt
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=pbft-network_default
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: peer node start
        ports:
        - 7051:7051
        volumes:
        - /var/run/:/host/var/run/
        - ../../config/pbft/crypto-config/peerOrganizations/org1.oslab.com/peers/peer0.org1.oslab.com/:/etc/hyperledger/msp/peer
        depends_on:
        - orderer0.oslab.com
        - orderer1.oslab.com
        - orderer2.oslab.com
        - orderer3.oslab.com

    peer1.org1.oslab.com:
        container_name: peer1.org1.oslab.com
        image: hyperledger/fabric-peer:1.4.4
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - CORE_LOGGING_LEVEL=ERROR
        - CORE_CHAINCODE_LOGGING_LEVEL=ERROR
        - CORE_CHAINCODE_LOGGING_SHIM=ERROR
        - CORE_CHAINCODE_EXECUTETIMEOUT=999999
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_PEER_ID=peer1.org1.oslab.com
        - CORE_PEER_ENDORSER_ENABLED=true
        - CORE_PEER_LOCALMSPID=Org1MSP
        - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp/
        - CORE_PEER_ADDRESS=peer1.org1.oslab.com:8051
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.oslab.com:8051
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/peer/tls/server.key
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/peer/tls/server.crt
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/tls/ca.crt
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=pbft-network_default
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: peer node start
        ports:
        - 8051:7051
        volumes:
        - /var/run/:/host/var/run/
        - ../../config/pbft/crypto-config/peerOrganizations/org1.oslab.com/peers/peer1.org1.oslab.com/:/etc/hyperledger/msp/peer
        depends_on:
        - orderer0.oslab.com
        - orderer1.oslab.com
        - orderer2.oslab.com
        - orderer3.oslab.com

    peer0.org2.oslab.com:
        container_name: peer0.org2.oslab.com
        image: hyperledger/fabric-peer:1.4.4
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - CORE_LOGGING_LEVEL=ERROR
        - CORE_CHAINCODE_LOGGING_LEVEL=ERROR
        - CORE_CHAINCODE_LOGGING_SHIM=ERROR
        - CORE_CHAINCODE_EXECUTETIMEOUT=999999
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_PEER_ID=peer0.org2.oslab.com
        - CORE_PEER_ENDORSER_ENABLED=true
        - CORE_PEER_LOCALMSPID=Org2MSP
        - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp/
        - CORE_PEER_ADDRESS=peer0.org2.oslab.com:9051
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.oslab.com:9051
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/peer/tls/server.key
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/peer/tls/server.crt
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/tls/ca.crt
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=pbft-network_default
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: peer node start
        ports:
        - 9051:7051
        volumes:
        - /var/run/:/host/var/run/
        - ../../config/pbft/crypto-config/peerOrganizations/org2.oslab.com/peers/peer0.org2.oslab.com/:/etc/hyperledger/msp/peer
        depends_on:
        - orderer0.oslab.com
        - orderer1.oslab.com
        - orderer2.oslab.com
        - orderer3.oslab.com
        
    peer1.org2.oslab.com:
        container_name: peer1.org2.oslab.com
        image: hyperledger/fabric-peer:1.4.4
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - CORE_LOGGING_LEVEL=ERROR
        - CORE_CHAINCODE_LOGGING_LEVEL=ERROR
        - CORE_CHAINCODE_LOGGING_SHIM=ERROR
        - CORE_CHAINCODE_EXECUTETIMEOUT=999999
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_PEER_ID=peer1.org2.oslab.com
        - CORE_PEER_ENDORSER_ENABLED=true
        - CORE_PEER_LOCALMSPID=Org2MSP
        - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp/
        - CORE_PEER_ADDRESS=peer1.org2.oslab.com:10051
        - CORE_PEER_GOSSIP_USELEADERELECTION=true
        - CORE_PEER_GOSSIP_ORGLEADER=false
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.oslab.com:10051
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/msp/peer/tls/server.key
        - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/msp/peer/tls/server.crt
        - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/msp/peer/tls/ca.crt
        - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=pbft-network_default
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: peer node start
        ports:
        - 10051:7051
        volumes:
        - /var/run/:/host/var/run/
        - ../../config/pbft/crypto-config/peerOrganizations/org2.oslab.com/peers/peer1.org2.oslab.com/:/etc/hyperledger/msp/peer
        depends_on:
        - orderer0.oslab.com
        - orderer1.oslab.com
        - orderer2.oslab.com
        - orderer3.oslab.com
