version: '2'

networks:
    zookeeper:
        driver: bridge
        ipam:
            config:
            - subnet: 172.55.0.0/24
              gateway: 172.55.0.1

services:
    zookeeper0:
      container_name: zookeeper0
      image: hyperledger/fabric-zookeeper:latest
      restart: always
      ports:
      - 2181:2181
      - '2888'
      - '3888'
      environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=172.55.0.2:2888:3888 server.2=172.55.0.3:2888:3888 server.3=172.55.0.4:2888:3888
      networks:
        zookeeper:
          ipv4_address: 172.55.0.2

    zookeeper1:
      container_name: zookeeper1
      image: hyperledger/fabric-zookeeper:latest
      restart: always
      ports:
      - 2182:2181
      - '2888'
      - '3888'
      environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=172.55.0.2:2888:3888 server.2=172.55.0.3:2888:3888 server.3=172.55.0.4:2888:3888
      networks:
        zookeeper:
          ipv4_address: 172.55.0.3

    zookeeper2:
      container_name: zookeeper2
      image: hyperledger/fabric-zookeeper:latest
      restart: always
      ports:
      - 2183:2181
      - '2888'
      - '3888'
      environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=172.55.0.2:2888:3888 server.2=172.55.0.3:2888:3888 server.3=172.55.0.4:2888:3888
      networks:
        zookeeper:
          ipv4_address: 172.55.0.4