
---

Organizations:
- &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/oslab-com/msp
    AdminPrincipal: Role.MEMBER

- &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: crypto-config/peerOrganizations/org1-oslab-com/msp
    AdminPrincipal: Role.ADMIN
    AnchorPeers:
    - Host: peer0
      Port: 7051

- &Org2
    Name: Org2MSP
    ID: Org2MSP
    MSPDir: crypto-config/peerOrganizations/org2-oslab-com/msp
    AdminPrincipal: Role.ADMIN
    AnchorPeers:
    - Host: peer3
      Port: 7051

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    Addresses:  
        - orderer0:7050
        - orderer1:7050
        - orderer2:7050
    
    BatchTimeout: 20s
    BatchSize:
        MaxMessageCount: 100
        AbsoluteMaxBytes: 500 MB
        PreferredMaxBytes: 512 KB

    MaxChannels: 1
    EtcdRaft:
        Consenters:
        - Host: orderer0
          Port: 7050
          ClientTLSCert: crypto-config/ordererOrganizations/oslab-com/orderers/orderer0-oslab-com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/oslab-com/orderers/orderer0-oslab-com/tls/server.crt
        - Host: orderer1
          Port: 7050
          ClientTLSCert: crypto-config/ordererOrganizations/oslab-com/orderers/orderer1-oslab-com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/oslab-com/orderers/orderer1-oslab-com/tls/server.crt
        - Host: orderer2
          Port: 7050
          ClientTLSCert: crypto-config/ordererOrganizations/oslab-com/orderers/orderer2-oslab-com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/oslab-com/orderers/orderer2-oslab-com/tls/server.crt
        
    Organizations:

Application: &ApplicationDefaults
    Organizations:

Profiles:
    OrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
            - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                - *Org1
                - *Org2
    ChannelConfig:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - *Org1
            - *Org2
