apiVersion: v1
kind: PersistentVolume
metadata:
  name: ca-org1-oslab-com-pv1
  labels:
    type: local
    name: ca-org1-volume1
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/oslab/go/src/github.com/consensus-performance/caliper_es/network/config/raft/crypto-config/peerOrganizations/org1.oslab.com/tlsca"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-org1-oslab-com-claim1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  selector:
    matchLabels:
      name: ca-org1-volume1
