---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ca-org1-oslab-com-pv0
  labels:
    type: local
    name: ca-org1-oslab-com-volume0
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/oslab/go/src/github.com/consensus-performance/caliper_es/network/config/raft/crypto-config/peerOrganizations/org1.oslab.com/ca/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-org1-oslab-com-claim0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  selector:
    matchLabels:
      name: ca-org1-oslab-com-volume0
