apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-org2-oslab-com
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ca-org2-oslab-com
  template:
    metadata:
      labels:
        name: ca-org2-oslab-com
    spec:
      containers:
        - args:
            - sh
            - -c
            - fabric-ca-server start -b admin:adminpw -d
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca.org2.oslab.com-cert.pem
            - name: FABRIC_CA_SERVER_CA_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-config/ca2_key
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca.org2.oslab.com
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: /etc/hyperledger/fabric-ca-server-tls/tlsca.org2.oslab.com-cert.pem
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: /etc/hyperledger/fabric-ca-server-tls/ca2_tls_key
          image: hyperledger/fabric-ca:1.4.4
          name: ca-org2-oslab-com
          ports:
            - containerPort: 7054
          volumeMounts:
            - mountPath: /etc/hyperledger/fabric-ca-server-config
              name: ca-org2-oslab-com-claim0
            - mountPath: /etc/hyperledger/fabric-ca-server-tls
              name: ca-org2-oslab-com-claim1
      restartPolicy: Always
      volumes:
        - name: ca-org2-oslab-com-claim0
          persistentVolumeClaim:
            claimName: ca-org2-oslab-com-claim0
        - name: ca-org2-oslab-com-claim1
          persistentVolumeClaim:
            claimName: ca-org2-oslab-com-claim1
