#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'

networks:
    orderer:
        driver: bridge
        ipam:
            config:
            - subnet: 172.51.0.0/24
              gateway: 172.51.0.1

services:
    orderer0.oslab.com:
        container_name: orderer0.oslab.com
        image: hyperledger/fabric-orderer:1.4.4
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/channel-artifacts/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        ports:
        - 7050:7050
        volumes:
        - ../../config/raft:/etc/hyperledger/configtx
        - ../../config/raft/crypto-config/ordererOrganizations/oslab.com/orderers/orderer0.oslab.com/:/etc/hyperledger/msp/orderer
        extra_hosts:
        - ca.org1.oslab.com:172.54.0.2
        - orderer1.oslab.com:172.51.0.3
        - orderer2.oslab.com:172.51.0.4
        networks:
          orderer:
              ipv4_address: 172.51.0.2

    orderer1.oslab.com:
        container_name: orderer1.oslab.com
        image: hyperledger/fabric-orderer:1.4.4
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/channel-artifacts/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        ports:
        - 8050:7050
        volumes:
        - ../../config/raft/:/etc/hyperledger/configtx
        - ../../config/raft/crypto-config/ordererOrganizations/oslab.com/orderers/orderer1.oslab.com/:/etc/hyperledger/msp/orderer
        extra_hosts:
        - ca.org1.oslab.com:172.54.0.2
        - orderer0.oslab.com:172.51.0.2
        - orderer2.oslab.com:172.51.0.4
        networks:
          orderer:
              ipv4_address: 172.51.0.3

    orderer2.oslab.com:
        container_name: orderer2.oslab.com
        image: hyperledger/fabric-orderer:1.4.4
        environment:
        - FABRIC_LOGGING_SPEC=error:error
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/channel-artifacts/genesis.block
        - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
        - ORDERER_GENERAL_TLS_ENABLED=true
        - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/msp/orderer/tls/ca.crt]
        - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/etc/hyperledger/msp/orderer/tls/server.crt
        - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/etc/hyperledger/msp/orderer/tls/server.key
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        ports:
        - 9050:7050
        volumes:
        - ../../config/raft/:/etc/hyperledger/configtx
        - ../../config/raft/crypto-config/ordererOrganizations/oslab.com/orderers/orderer2.oslab.com/:/etc/hyperledger/msp/orderer
        extra_hosts:
        - ca.org1.oslab.com:172.54.0.2
        - orderer0.oslab.com:172.51.0.2
        - orderer1.oslab.com:172.51.0.3
        networks:
          orderer:
              ipv4_address: 172.51.0.4
